# Generated by Django 4.2.7 on 2023-12-01 06:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('slug', models.SlugField(editable=False)),
                ('cimage', models.ImageField(upload_to='images/categories')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('p_name', models.CharField(max_length=50)),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_image', models.ImageField(upload_to='images/products')),
                ('p_description', ckeditor.fields.RichTextField()),
                ('p_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_shop_user.category')),
            ],
        ),
    ]
