# Generated by Django 4.2.7 on 2023-12-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_user', '0002_alter_product_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_image',
            field=models.FileField(blank=True, null=True, upload_to='images/products'),
        ),
    ]
