# Generated by Django 4.2.7 on 2023-12-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_user', '0005_alter_product_p_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagegallery',
            name='image',
            field=models.ImageField(default='/static/images/nope-not-here.webp', upload_to='product-galleries'),
        ),
    ]
