# Generated by Django 4.2.7 on 2023-12-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_user', '0009_alter_product_is_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
    ]
