# Generated by Django 4.2.7 on 2023-12-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_user', '0013_alter_product_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
