# Generated by Django 4.2.7 on 2023-12-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_user', '0024_alter_product_p_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_name',
            field=models.CharField(max_length=100),
        ),
    ]
