# Generated by Django 4.2.7 on 2023-12-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_user', '0026_alter_product_p_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=150),
        ),
    ]
