# Generated by Django 4.2.7 on 2023-12-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_user', '0027_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cname',
            field=models.CharField(max_length=50),
        ),
    ]
