# Generated by Django 4.2.7 on 2023-11-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_user',
            name='phone_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
