# Generated by Django 4.2.7 on 2023-11-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_admin', '0002_alter_auth_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_user',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
