# Generated by Django 4.2.7 on 2023-12-02 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_user', '0001_initial'),
        ('e_shop_admin', '0003_alter_auth_user_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='images/crousal')),
                ('link_type', models.CharField(choices=[('product', 'product'), ('category', 'category')])),
                ('link_category', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_shop_user.category')),
                ('link_product', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_shop_user.product')),
            ],
        ),
    ]
