# Generated by Django 4.2.7 on 2023-12-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_admin', '0005_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profile_user',
        ),
    ]
