# Generated by Django 4.2.7 on 2023-12-11 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_admin', '0006_rename_profile_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
