# Generated by Django 4.2.7 on 2023-12-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_admin', '0011_rename_u_profile_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_user',
            name='forget_password_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile_user',
        ),
    ]
