# Generated by Django 4.2.7 on 2023-12-12 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_admin', '0013_auth_user_expire_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_user',
            name='expire_token',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='auth_user',
            name='forget_password_token',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
