# Generated by Django 4.2.7 on 2023-12-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop_admin', '0015_wishlist_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist_view',
        ),
    ]
